In [3]:
import numpy as np
import pandas as pd

index=pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns=pd.MultiIndex.from_product([['bob','guido','sue'],['HR','Temp']],names=['name','dept'])
data=np.round(np.random.randn(4,6),1)
health_data=pd.DataFrame(data,index=index,columns=columns)
print(health_data)

name        bob      guido       sue
dept         HR Temp    HR Temp   HR Temp
year visit
2013 1     -1.6  1.1   1.4  0.0 -2.0 -0.0
     2      1.2 -0.3   0.2  0.1 -1.0 -0.9
2014 1      0.7 -0.8   0.2  1.4 -0.7 -0.5
     2     -1.4  1.0  -1.0 -0.5  0.8  0.1

In [4]:
health_data['guido']

dept         HR  Temp
year visit
2013 1      1.4   0.0
     2      0.2   0.1
2014 1      0.2   1.4
     2     -1.0  -0.5

In [5]:
health_data.iloc[:2,:2]

name        bob
dept         HR Temp
year visit
2013 1     -1.6  1.1
     2      1.2 -0.3

In [6]:
health_data.loc[:,('bob','HR')]

year  visit
2013  1       -1.6
      2        1.2
2014  1        0.7
      2       -1.4
Name: (bob, HR), dtype: float64

In [7]:
idx=pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

name        bob guido  sue
dept         HR    HR   HR
year visit
2013 1     -1.6   1.4 -2.0
2014 1      0.7   0.2 -0.7

In [8]:
index=pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data=pd.Series(np.random.rand(6),index=index)
data.index.names=['char','int']
data

char  int
a     1      0.766741
      2      0.838121
c     1      0.897201
      2      0.182442
b     1      0.655646
      2      0.102057
dtype: float64

In [20]:
data=data.sort_index()
data

char  int
a     1      0.766741
      2      0.838121
b     1      0.655646
      2      0.102057
c     1      0.897201
      2      0.182442
dtype: float64

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
fare=titanic.pivot_table('survived',index='sex',columns='class')
fare

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [13]:
pivot = pd.pivot_table( data=titanic,
    values='fare', 
    index='sex', 
    columns='class', 
    aggfunc='mean'
)
print(pivot)

class        First     Second      Third
sex
female  106.125798  21.970121  16.118810
male     67.226127  19.741782  12.661633

In [21]:
age= pd.cut(titanic['age'],[0,8,18])
age

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
886    NaN
887    NaN
888    NaN
889    NaN
890    NaN
Name: age, Length: 891, dtype: category
Categories (2, interval[int64, right]): [(0, 8] < (8, 18]]

In [29]:
age= pd.qcut(titanic['age'],q=4)
age

0       (20.125, 28.0]
1         (28.0, 38.0]
2       (20.125, 28.0]
3         (28.0, 38.0]
4         (28.0, 38.0]
            ...
886     (20.125, 28.0]
887    (0.419, 20.125]
888                NaN
889     (20.125, 28.0]
890       (28.0, 38.0]
Name: age, Length: 891, dtype: category
Categories (4, interval[float64, right]): [(0.419, 20.125] < (20.125, 28.0] < (28.0, 38.0] < (38.0, 80.0]]

In [30]:
q2=titanic.pivot_table(index='sex',columns='class',aggfunc={'age':min,'fare':min})
q2

         age                  fare
class  First Second Third    First Second Third
sex
female  2.00    2.0  0.75  25.9292   10.5  6.75
male    0.92    NaN  0.42   0.0000    0.0  0.00

In [34]:
q1=titanic.pivot_table('survived',index='alone',columns='class')
q1

class     First    Second     Third
alone
False  0.728972  0.637500  0.299401
True   0.532110  0.346154  0.212963

In [2]:
#50
import pandas as pd

data = {
    'department': ['CSE', 'AIML', 'ECE', 'CSE', 'AIML', 'ECE',
                   'CSE', 'AIML', 'ECE', 'CSE', 'AIML', 'ECE'],
    'gender': ['M', 'F', 'M', 'F', 'M', 'F',
               'M', 'F', 'M', 'F', 'M', 'F'],
    'salary': [60000, 65000, 55000, 62000, 70000, 58000,
               68000, 72000, 61000, 64000, 75000, 60000]
}

df = pd.DataFrame(data)

print("Employee DataFrame:")
print(df)

pivot_table = pd.pivot_table(
    df,
    values='salary',
    index='gender',
    columns='department',
    aggfunc='mean'
)

print("\nAverage Salary Pivot Table:")
print(pivot_table)

Employee DataFrame:
   department gender  salary
0         CSE      M   60000
1        AIML      F   65000
2         ECE      M   55000
3         CSE      F   62000
4        AIML      M   70000
5         ECE      F   58000
6         CSE      M   68000
7        AIML      F   72000
8         ECE      M   61000
9         CSE      F   64000
10       AIML      M   75000
11        ECE      F   60000

Average Salary Pivot Table:
department     AIML      CSE      ECE
gender
F           68500.0  63000.0  59000.0
M           72500.0  64000.0  58000.0

In [3]:
#51
import pandas as pd
pivot_count = pd.pivot_table(
    df,
    values='salary',
    index='gender',
    columns='department',
    aggfunc='count'
)

print(pivot_count)

department  AIML  CSE  ECE
gender
F              2    2    2
M              2    2    2

In [4]:
#52
pivot_totals = pd.pivot_table(
    df,
    values='salary',
    index='gender',
    columns='department',
    aggfunc='mean',
    margins=True,
    margins_name='Total'
)

print(pivot_totals)

department     AIML      CSE      ECE         Total
gender
F           68500.0  63000.0  59000.0  63500.000000
M           72500.0  64000.0  58000.0  64833.333333
Total       70500.0  63500.0  58500.0  64166.666667

In [5]:
#53
import pandas as pd

df['age'] = [22, 25, 28, 30, 35, 40,
             24, 27, 32, 38, 42, 45]

# Create age groups
df['age_group'] = pd.cut(
    df['age'],
    bins=[20, 29, 39, 50],
    labels=['Junior', 'Mid', 'Senior']
)

pivot_age = pd.pivot_table(
    df,
    values='salary',
    index='age_group',
    columns='department',
    aggfunc='mean'
)

print(pivot_age)

department     AIML      CSE      ECE
age_group
Junior      68500.0  64000.0  55000.0
Mid         70000.0  63000.0  61000.0
Senior      75000.0      NaN  59000.0

In [6]:
#54
pivot_multi = pd.pivot_table(
    df,
    values=['salary', 'age'],
    index='department',
    aggfunc={
        'salary': 'sum',
        'age': 'mean'
    }
)

print(pivot_multi)

              age  salary
department
AIML        32.25  282000
CSE         28.50  254000
ECE         36.25  234000

In [9]:
#55
import pandas as pd
import seaborn as sns

# Load Titanic dataset
titanic = sns.load_dataset('titanic')

pivot_titanic = pd.pivot_table(
    titanic,
    values='survived',
    index='sex',
    columns='class',
    aggfunc='mean',
    margins=True
)

print(pivot_titanic)

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838